### ISSUE TITLE
[GUI] Cambiar cursor para los botones "clickeables"

### ISSUE THREAD

**Issue by gonetil** [J-Josu/RobotScript#4]
Para ayudar al usuario a darse cuenta que puede hacer clic en los botones de la barra superior (abrir, bajar, compilar, ejecutar, vista, etc..) sería bueno que al poner el mouse sobre ellos se vea un cursor tipo puntero.
Esto se puede resolver con una sencilla regla de CSS, algo así:

```css
button.tool--button {
  cursor: pointer;
}
```
